config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
                               sessions: 'users/sessions'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get 'images', to: 'images#index'
  get 'comments', to: 'comments#all'
  get 'profile', to: 'static_pages#profile'

  resources :categories, param: :slug, except: [:edit, :update] do
    resources :subscriptions, only: [:create, :destroy]
    resources :images, except: [:update, :edit] do
      resources :comments, shallow: true, except: [:index, :update, :edit, :show, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get 'images/new', to: 'images#extended_new'
  match "images/new" => "images#extended_create", :via => :post

  get 'categories/:category_slug/:id', to: 'images#show', as: 'category_image_new'
  mount Resque::Server.new, at: "/resque"

end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :images, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_category, only: %i[show destroy]

  def index
    @categories = Category.all
  end

  def show
    @images = @category.images.page(params[:page])
    @pre_subscribe = @category.subscriptions.find { |subscription| subscription.user_id == current_user.id} if current_user
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to @category, success: I18n.t('flash.category.created')
    else
      render :new
    end
  end

  def destroy
    # current_user.categories.find(@category.id).destroy
    if current_user.id == @category.user_id
      @category.destroy
      redirect_to profile_path, success: I18n.t('flash.category.removed')
    else
      redirect_to profile_path, danger: I18n.t('flash.category.didnt_remove')
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def find_category
    @category = Category.find_by_slug(params[:slug])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_errors.html.haml
- if @category && @category.errors.any?
  - @category.errors.full_messages.each do |message|
    .container-fluid.p-0
      %div{:class => "alert alert-danger"}
        %button{:class => 'close', "data-dismiss" => 'alert'} &times;
        = message

app/views/categories/_form.html.haml
= form_with(model: @category, local: true) do |f|
  .form-group
    = f.label :title, class: 'control-label'
    = f.text_field :title, class: 'form-control'
    = f.submit t('links.save'), :class => "btn btn-dark my-2"

app/views/categories/index.html.haml
%h1.text-center= t('categories.index.title')
- if user_signed_in?
  .row
    .col-12.d-flex.justify-content-center
      = link_to t('links.create_new_category'), new_category_path, class: "btn btn-dark my-3"

- @categories.each_slice(3).each do |row|
  .category.row
    - row.each do |category|
      .col-lg-4.col-12.px-1
        .position-relative.zindex-modal
          .title #{category.title.capitalize}
          - if popular_image(category.id)
            = link_to image_tag("#{popular_image(category.id).src.url(:thumb)}", :class => "img-fluid mt-2"), category_path(category)
          - else
            = link_to image_tag('no-image.jpg', :class => "img-fluid mt-2"), category_path(category)

app/views/categories/new.html.haml
%h1.text-center
  = t('categories.new.title')

= render 'form'

app/views/categories/show.html.haml
%h1.text-center= @category.title.capitalize
.row
  .col-12.d-flex.justify-content-center
    - if user_signed_in?
      - if @pre_subscribe
        = link_to t('categories.show.unsubscribe'), category_subscription_path(@category, @pre_subscribe), method: :delete, class: "btn btn-dark my-3"
      - else
        = link_to t('categories.show.subscribe'), category_subscriptions_path(@category), method: :post, class: "btn btn-dark my-3"
    - else
      = link_to t('categories.show.subscribe'), category_subscriptions_path(@category), method: :post, class: "btn btn-dark my-3"

.row
  - @images.to_a.each_slice(3).each do |column|
    .column
      - column.each do |image|
        .position-relative
          - if user_signed_in?
            = link_to image_tag("#{image.src.url(:thumb)}", :class => "img-fluid"),
                              category_image_new_path(category_slug: image.category.slug,
                              id: image.id) if image.src?
            .overlay.d-flex.justify-content-end.align-items-center
              = fa_icon('heart', type: :far)
              %span.m-1= image.likes.size

          - else
            = image_tag("#{image.src.url(:thumb)}", class: 'images', 'data-src': "#{image.src.url}") if image.src?
            .overlay.d-flex.justify-content-end.align-items-center
              = fa_icon('heart', type: :far)
              %span.m-1= image.likes.size
            #myModal.modal
              .close &times
              %span= image_tag("#{image.src.url}", id: "img-modal", class: "modal-content")

- if user_signed_in?
  = render 'images/form'

= paginate @images