config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
                               sessions: 'users/sessions'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get 'images', to: 'images#index'
  get 'comments', to: 'comments#all'
  get 'profile', to: 'static_pages#profile'

  resources :categories, param: :slug, except: [:edit, :update] do
    resources :subscriptions, only: [:create, :destroy]
    resources :images, except: [:update, :edit] do
      resources :comments, shallow: true, except: [:index, :update, :edit, :show, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get 'images/new', to: 'images#extended_new'
  match "images/new" => "images#extended_create", :via => :post

  get 'categories/:category_slug/:id', to: 'images#show', as: 'category_image_new'
  mount Resque::Server.new, at: "/resque"

end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :src, file_size: { less_than: 50.megabytes }
  paginates_per 6
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_category, only: %i[create show destroy]
  before_action :find_image, only: %i[show destroy]
  before_action :find_category_by_id, only: [:extended_create]
  before_action :create_common, only: %i[create extended_create]
  before_action :new_common, only: %i[new extended_new]
  before_action :find_category_all, only: [:extended_new]

  def index
    @images = Image.select('images.*, (likes_count + comments_count) AS i_count').order('i_count DESC').page(params[:page])
  end

  def show
    @pre_like = @image.likes.find { |like| like.user_id == current_user.id }
  end

  def new
  end

  def create
  end

  def extended_new
  end

  def extended_create
  end

  def create_common
    if params[:image].blank?
      redirect_to @category, danger: I18n.t('flash.image.select')
    else
      @image = @category.images.new(image_params.merge( { user_id: current_user.id } ))
      if @image.save && @image.errors.empty?
        id = @image.id
        Resque.enqueue(NewImageSendEmail, id)
        redirect_to @category, success: I18n.t('flash.image.saved')
      else
        render :new, danger: I18n.t('flash.image.didnt_save')
      end
    end
  end

  private

  def find_category
    @category = Category.friendly.find(params[:category_slug])
  end

  def find_category_by_id
    @category = Category.find(image_params[:category_id])
  end

  def find_category_all
    @category_all = Category.all
  end

  def find_image
    @image = @category.images.find(params[:id])
  end

  def new_common
    @image = Image.new
  end


  def image_params
    params.require(:image).permit(:src, :category_id)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_errors.html.haml
- if @image && @image.errors.any?
  - @image.errors.full_messages.each do |message|
    .container-fluid.p-0
      %div{:class => "alert alert-danger"}
        %button{:class => 'close', "data-dismiss" => 'alert'} &times;
        = message

app/views/images/_form.html.haml
%h4.text-center.mt-2= t('images.form.title')
= form_with(model: [@category, @category.images.build ], local: true, class: "d-flex justify-content-between align-items-center btn btn-light rounded-0 m-0") do |f|
  = f.file_field :src, :class => "form-control-file"
  = f.submit t('links.save'), :class => "btn btn-dark"

app/views/images/extended_new.html.haml
%h4.text-center.mt-2= t('images.form.title')
= form_with(model: @image, url: images_new_path, local: true) do |f|
  .form-group
    = f.label(:category_id)
    = f.select :category_id, @category_all.collect {|c| [ c.title, c.id ] }, { include_blank: true }, :class => "form-control"
  .form-group
    = f.file_field :src, :class => "form-control-file"
  = f.submit t('links.save'), :class => "btn btn-dark"

app/views/images/index.html.haml
.container
  %h1.text-center= t('images.index.title')

  .row
    - @images.to_a.each_slice(3).each do |column|
      .column
        - column.each do |image|
          .position-relative
            - if user_signed_in?
              .overlay.d-flex.justify-content-end.align-items-center
                = fa_icon('heart', type: :far)
                %span.m-1= image.likes.size
              - if image.src.url(:thumb)
                = link_to image_tag("#{image.src.url(:thumb)}"), category_image_new_path(category_slug: image.category.slug, id: image.id) if image.src?
              - else
                = link_to image_tag('no-image.jpg', :class => "img-fluid mt-2"), category_image_new_path(category_slug: image.category.slug, id: image.id)
            - else
              .overlay.d-flex.justify-content-end.align-items-center
                = fa_icon('heart', type: :far)
                %span.m-1= image.likes.size
              = image_tag("#{image.src.url(:thumb)}", class: 'images', 'data-src': "#{image.src.url}") if image.src?
              #myModal.modal
                .close &times
                = image_tag("#{image.src.url}", id: "img-modal", class: "modal-content")

  = paginate @images

app/views/images/new.html.haml
%h1.text-center= t('images.new.title')

= render 'images/form'

app/views/images/show.html.haml
.container
  .img-show.position-relative
    = image_tag "#{@image.src.url}", :class => "img-fluid mb-4" if @image.src?

    - if @pre_like
      .like-img.d-flex.align-items-center.justify-content-between
        .comments
          %h4#comments-link= t('images.show.comment')
        = link_to category_image_like_path(@category, @image, @pre_like), method: :delete, class: 'link-delete' do
          .block-like.d-flex.align-items-center.justify-content-end
            = fa_icon('heart', type: :fas, size: '2x')
            %h5.m-1= @image.likes.size
    - else
      .like-img.d-flex.align-items-center.justify-content-between
        .comments
          %h4#comments-link= t('images.show.comment')
        = link_to category_image_likes_path(@category, @image), method: :post, class: 'link-create' do
          .block-like.d-flex.align-items-center.justify-content-end
            = fa_icon('heart', type: :far, size: '2x')
            %h5.m-1= @image.likes.size

  #comments-section.container.d-none
    %h5.my-4= t('images.show.add_comment')
    #comments
      = render 'comments/form'

    - if @image.comments.first.id?
      = render @image.comments.desc