config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
                               sessions: 'users/sessions'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get 'images', to: 'images#index'
  get 'comments', to: 'comments#all'
  get 'profile', to: 'static_pages#profile'

  resources :categories, param: :slug, except: [:edit, :update] do
    resources :subscriptions, only: [:create, :destroy]
    resources :images, except: [:update, :edit] do
      resources :comments, shallow: true, except: [:index, :update, :edit, :show, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get 'images/new', to: 'images#extended_new'
  match "images/new" => "images#extended_create", :via => :post

  get 'categories/:category_slug/:id', to: 'images#show', as: 'category_image_new'
  mount Resque::Server.new, at: "/resque"

end

app/models/action.rb
class Action < ApplicationRecord
  has_many :logging_user_actions, dependent: :destroy
end

app/models/admin_image.rb
# frozen_string_literal: true

class AdminImage < ApplicationRecord
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :images, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, uniqueness: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :image, counter_cache: true
  belongs_to :user
  validates :commenter, :body, presence: true
  paginates_per 5
  scope :desc, -> { order(created_at: :desc) }
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :src, file_size: { less_than: 50.megabytes }
  paginates_per 6
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :image, counter_cache: true
  belongs_to :user
end

app/models/logging_user_action.rb
# frozen_string_literal: true

class LoggingUserAction < ApplicationRecord
  belongs_to :user
  belongs_to :action
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :category, counter_cache: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, :trackable
  validates :username, presence: true, uniqueness: true
  has_many :categories, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :logging_user_actions, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid, username: auth.info.name).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.logins_before_captcha
    3
  end

  def after_confirmation
    welcome_send
  end

  def welcome_send
    Resque.enqueue(WelcomeSendEmail, [self.email, self.username])
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_category, only: %i[create show destroy]
  before_action :find_image, only: %i[show destroy]
  before_action :find_category_by_id, only: [:extended_create]
  before_action :create_common, only: %i[create extended_create]
  before_action :new_common, only: %i[new extended_new]
  before_action :find_category_all, only: [:extended_new]

  def index
    @images = Image.select('images.*, (likes_count + comments_count) AS i_count').order('i_count DESC').page(params[:page])
  end

  def show
    @pre_like = @image.likes.find { |like| like.user_id == current_user.id }
  end

  def new
  end

  def create
  end

  def extended_new
  end

  def extended_create
  end

  def create_common
    if params[:image].blank?
      redirect_to @category, danger: I18n.t('flash.image.select')
    else
      @image = @category.images.new(image_params.merge( { user_id: current_user.id } ))
      if @image.save && @image.errors.empty?
        id = @image.id
        Resque.enqueue(NewImageSendEmail, id)
        redirect_to @category, success: I18n.t('flash.image.saved')
      else
        render :new, danger: I18n.t('flash.image.didnt_save')
      end
    end
  end

  private

  def find_category
    @category = Category.friendly.find(params[:category_slug])
  end

  def find_category_by_id
    @category = Category.find(image_params[:category_id])
  end

  def find_category_all
    @category_all = Category.all
  end

  def find_image
    @image = @category.images.find(params[:id])
  end

  def new_common
    @image = Image.new
  end


  def image_params
    params.require(:image).permit(:src, :category_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!, :find_image
  before_action :find_like, only: [:destroy]
  after_action :logging_likes, only: %i[create destroy]

  def create
    @like = @image.likes.create(user_id: current_user.id) unless already_liked?
    redirect_to category_image_path(@category, @image)
  end

  def destroy
    if already_liked?
      @like.destroy
    end
    redirect_to category_image_path(@category, @image)
  end

  private

  def find_image
    @image = Image.find(params[:image_id])
    @category = Category.find(@image.category_id)
  end

  def already_liked?
    Like.where(user_id: current_user.id, image_id:
        params[:image_id]).exists?
  end

  def find_like
    @like = @image.likes.find(params[:id])
  end

  def pre_like
    @pre_like = @image.likes.find { |like| like.user_id == current_user.id }
  end

  def logging_likes
    LoggingUserAction.new(user_id: current_user.id,
                          action_id: "#{Action.find_by_action_type('likes').id}",
                          action_path: request.original_url).save if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
        success: 'alert-success',
        error: 'alert-danger',
        danger: 'alert-danger',
        alert: 'alert-warning',
        notice: 'alert-info',
    }[name.to_sym] || name
  end

  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/upload_images/_form.html.haml
= semantic_form_for :upload_images, builder: ActiveAdmin::FormBuilder, url: { action: :grab } do |f|
  =f.inputs do
    =f.input :url, label: false, placeholder: 'Paste your URL'
    =f.action :submit, label: 'Get Images'

app/views/layouts/_errors.html.haml
- flash.each do |name, message|
  .container-fluid.p-2
    %div{:class => "alert #{bootstrap_class_for(name)}"}
      %button{:class => 'close', "data-dismiss" => 'alert'} &times;
      = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Gallery
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .row.mt-4
      .col.text-center
        %a.navbar-brand.mx-auto{:href => root_path}
          = image_tag('logo.resized.png', :class => "d-flex text-align-center")
          .logo.mt-3
            %em
              %strong Gallery
          %hr
    %nav.container.navbar.navbar-expand-lg.bg-light.navbar-light.locale
      %ul.navbar-nav.mx-auto
        %li.nav-item.border.p-1
          = link_to "ru", { locale: :ru }, class: (I18n.locale == :ru ? "nav-link active" : "nav-link")
        %li.nav-item.border.border-left-0.p-1
          = link_to "en", { locale: :en }, class: (I18n.locale == :en ? "nav-link active" : "nav-link")
    %nav.container-fluid.navbar.navbar-expand-lg.sticky-top.bg-light.navbar-light.menu
      .w-75.mx-auto.text-center
        %button.navbar-toggler{:class => "mx-auto", :data => {:target => "#navbarSupportedContent", :toggle => "collapse"}, :type => "button", :aria => {:controls => "navbarSupportedContent", :expanded => "false", :label => "Toggle navigation"}}
          %span.navbar-toggler-icon
        .collapse.navbar-collapse#navbarSupportedContent
          %ul.navbar-nav.mr-auto
            %li.nav-item.dropdown{:class => ("active" if controller_name == "categories")}
              = link_to t('menu.categories'), root_path, class: "nav-link dropdown-toggle", id: "navbardrop",
                'data-toggle': "dropdown", 'aria-haspopup': "true", 'aria-expanded': "false"
              .dropdown-menu
                -rating_categories.each do |category|
                  = link_to "#{category.title.capitalize}", category_path(category), class: "dropdown-item"
                .dropdown-divider
                = link_to t('menu.all_categories'), categories_path, class: "dropdown-item"
            %li.nav-item{:class => ("active" if controller_name == "images")}
              = link_to t('menu.images'), images_path, class: "nav-link"
            %li.nav-item{:class => ("active" if controller_name == "comments")}
              = link_to t('menu.comments'), comments_path, class: "nav-link"
          %ul.navbar-nav
            - if user_signed_in?
              %li.nav-item{:class => current_class?('/profile')}
                = link_to t('menu.profile'), profile_path, class: "nav-link"
              %li.nav-item
                = link_to t('menu.exit'), destroy_user_session_path, method: :delete, class: "nav-link"
            - else
              %li.nav-item{:class => current_class?('/users/sign_in')}
                = link_to t('menu.sign_in'), new_user_session_path, class: "nav-link"
              %li.nav-item{:class => current_class?('/users/sign_up')}
                = link_to t('menu.registration'), new_user_registration_path, class: "nav-link"

    = render "categories/errors"
    = render "images/errors"
    = render "comments/errors"
    = render "layouts/errors"
    = render "devise/errors"

    - if controller_name == "static_pages"
      .container-fluid.p-2
        = yield
    - else
      .container.my-4
        = yield

    %footer
      .container-fluid.bg-light.text-dark
        .row
          .col-12.text-center
            %h4.m-2 Contacts
            .email
              = fa_icon('envelope', type: :far, size: '1x')
              gallery@gmail.com
            .icons.m-2
              = link_to "/", method: :get, :class => "rounded-circle m-1" do
                = fa_icon('facebook-f', type: :fab, size: '1x')
              = link_to "/", method: :get, :class => "rounded-circle m-1" do
                = fa_icon('vk', type: :fab, size: '1x')
              = link_to "/", method: :get, :class => "rounded-circle m-1" do
                = fa_icon('instagram', type: :fab, size: '1x')
            %p.text-center Copyright © 2019 Gallery

    %script{:src => 'https://www.google.com/recaptcha/api.js', :async => "", :defer => ""}